import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarDays, Check } from "lucide-react";
import { MedicalNotice } from "@/components/MedicalNotice";
import { PageHero } from "@/components/PageHero";
import { services } from "@/lib/data";
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const s=services.find(x=>x.slug===slug);return s?{title:s.name,description:`Learn about ${s.name.toLowerCase()} services at Summit Valley Medical Center in Austin.`}:{}}
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();const Icon=s.icon;const schema={"@context":"https://schema.org","@type":"MedicalClinic","name":`Summit Valley ${s.name}`,"description":s.text,"parentOrganization":{"@type":"MedicalOrganization","name":"Summit Valley Medical Center"}};return <><PageHero parent="Medical Services" title={s.name} description={s.text}/><section className="section"><div className="container content-grid"><article className="prose"><span className="service-icon"><Icon/></span><div className="business-disclosure" style={{marginTop:0}}><strong>Clinical evaluation required</strong><p>Procedures, appointment availability, and treatment suitability depend on individual clinical needs and professional evaluation.</p></div><h2>Our approach</h2><p>Summit Valley provides patient-centered {s.name.toLowerCase()} services grounded in evidence-based care and coordination with other qualified professionals. Treatment suitability is determined by a physician after an appropriate evaluation.</p><h2>Conditions and evaluations</h2><ul><li>Appropriate assessment for common and complex concerns</li><li>Preventive evaluation and risk-factor review where clinically appropriate</li><li>Diagnostic coordination based on individual clinical needs</li><li>Follow-up planning and referrals when indicated</li></ul><h2>Patient safety</h2><ul className="check-list"><li><Check/>Credentialed clinicians and defined clinical privileges</li><li><Check/>Informed consent and financial information before treatment</li><li><Check/>No guaranteed outcomes or one-size-fits-all treatment claims</li></ul><MedicalNotice/></article><aside className="side-card"><h2>Request an appointment</h2><p>A scheduler will confirm clinician and appointment availability. Online requests are not final confirmations.</p><Link href="/appointments" className="button button-primary"><CalendarDays size={17}/>Appointment request</Link><Link href="/services" className="button button-secondary">All services</Link></aside></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
